name: Bazel on multiple platforms

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Install Bazel
        run: apt-get update && apt-get install bazel@7.0.0
      - name: Use bazel
        run: bazel --version

      - name: Build
        run: bazel build //...

      - name: Test
        run: bazel test //...
