name: Bazel CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Bazel
        run: sudo apt install g++ unzip zip
          sudo apt-get install default-jdk
          chmod +x bazel-7.0.2-installer-linux-x86_64.sh
          ./bazel-7.0.2-installer-linux-x86_64.sh
      - name: Use bazel
        run: bazel --version

      - name: Build
        run: bazel build //...

      - name: Test
        run: bazel test //...
