name: Bazel CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macOS-13
    steps:
      # - uses: actions/checkout@v4
      # - uses: bazelbuild/setup-bazelisk@v3
      # - name: Mount bazel cache # Optional
      #   uses: actions/cache@v4
      #   with:
      #     path: "~/.cache/bazel"
      #     key: bazel
      - name: Install Bazel
        run: |
          brew update
          brew unlink bazelisk
          brew install bazel
          ls -lart
          bazel --version
      - name: Build
        run: bazel build //...

      - name: Test
        run: bazel test //...
